spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-conf-dev
    
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-conf-test

#需要保存为utf-8格式